language: node_js
node_js:
  - "8"
  - "7"
before_install:  
  - npm install -g npm
  - npm install
  - npm run dev-travis
script: npm run test
after_success: 
  - npm run coveralls
notifications:
  email: false